version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.10.2
    command: webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres/etl_db
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - ../dags:/opt/airflow/dags

  airflow-scheduler:
    image: apache/airflow:2.10.2
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres/etl_db
    depends_on:
      - postgres
    volumes:
      - ../dags:/opt/airflow/dags

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  spark-master:
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host 0.0.0.0
      --port 7077
      --webui-port 8080
    ports:
      - "8082:8080"
      - "7077:7077"
    volumes:
      - spark_data:/opt/spark/work-dir

  
  spark-worker:
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      --webui-port 8081
      --port 7078
      spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - spark_data:/opt/spark/work-dir

volumes:
  postgres_data:
  kafka_data:
  spark_data: