version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.10.2
    command: webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres/etl_db
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - ../dags:/opt/airflow/dags

  airflow-scheduler:
    image: apache/airflow:2.10.2
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres/etl_db
    depends_on:
      - postgres
    volumes:
      - ../dags:/opt/airflow/dags

volumes:
  postgres_data: